name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - setuptools<58
  - open-fonts
  - numpy>=1.16.4
  - seaborn<=0.9.0
  - python-igraph
  - pycairo
  - scipy=1.3.0
  - ipython
  - pandas=1.0.3
  - matplotlib=2.2.3
  - matplotlib-base=2.2.3
  - plotly<=2.7.0
  - jupyter
  - networkx=2.3
  - statsmodels
  - Jinja2>=2.10.1
  - requests
  - defusedxml
  - pydot
  - appdirs
  - sortedcontainers
  - pathos
  - openpyxl
  - pip
  - pip:
      - matplotlib_venn
      - bioservices==1.6
      - py2cytoscape==0.7.1
      - matplotlib_venn==0.11.5
      - wordcloud