name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  #  - graphviz
  - open-fonts
  - numpy>=1.16.4
  - seaborn<=0.9.0
  - python-igraph
  - pycairo
  - scipy=1.3.0
  - ipython
  - pandas=1.0.3
  - matplotlib<=3.0.0
  - plotly<=2.7.0
  - jupyter
  - networkx=2.3
  - statsmodels
  - Jinja2>=2.10.1
  - pyicu
  - wordcloud
  - py2cytoscape
  - requests
  - defusedxml
  - pydot
  - bioconda::bioservices
  - appdirs
  - sortedcontainers
  - pathos
  - openpyxl
  - pip
  - pip:
      - matplotlib_venn