name: magine_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - seaborn
  - python-igraph
  - pycairo
  - scipy
  - ipython
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - jupyter
  - networkx
  - pip
  - pip:
      - wordcloud
      - appdirs
      - sortedcontainers
      - bioservices
      - matplotlib_venn
      - py2cytoscape
      - pathos
      - openpyxl
      - pydot
      - defusedxml
      - requests
      - Jinja2
      - statsmodels