name: base
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - seaborn
  - python-igraph
  - pycairo
  - scipy
  - ipython
  - pandas
  - matplotlib
  - plotly
  - jupyter
  - networkx=2.3
  - statsmodels
  - Jinja2
  - pip
  - pip:
      - wordcloud
      - appdirs
      - sortedcontainers
      - bioservices
      - matplotlib_venn
      - py2cytoscape
      - pathos
      - openpyxl
      - pydot
      - defusedxml
      - requests