from magine.network_database_expansions.reactome.reactome_functional_interaction import ReactomeFunctionalInteraction
from magine.network_database_expansions.expansion_network import load_reactome_fi
__all__ = ['ReactomeFunctionalInteraction', 'load_reactome_fi']